version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    env_file:
      - ./.env
    ports:
      - "8080:80"
    depends_on:
      - backend
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
